# login mu IP is UK
API_KEY = 'API_KEYAPI_KEYAPI_KEYAPI_KEYAPI_KEYAPI_KEYAPI_KEYAPI_KEYAPI_KEYAPI_KEYAPI_KEY'
API_SECRET = 'API_SECRETAPI_SECRETAPI_SECRETAPI_SECRETAPI_SECRETAPI_SECRETAPI_SECRET'
EMAIL = 'vahid.zahani@gmail.com'

